 angular.module("myApp").controller("Assignment3Controller",function($scope){
    $scope.employee=[{
        Id:"1",
        name:"Rohit",
        technology:"Java"
    },
    {Id:"2",
    name:"Anshul",
    technology:"Android"
    },
    {Id:"3",
    name:"Rohan",
    technology:"C++"
    },
    {Id:"4",
    name:"Aishwarya",
    technology:"C"
    }];
    });